services:
  mongo:
    container_name: "mongo"
    image: mongo:latest
    command: [--replSet, my-replica-set, --bind_ip_all, --port, "27017"]
    ports:
      - "27017:27017"
    healthcheck:
      test: test $$(mongosh --port 27017 --quiet --eval "try {rs.initiate({_id:'my-replica-set',members:[{_id:0,host:\"mongo:27017\"}]})} catch(e) {rs.status().ok}") -eq 1
      interval: 10s
      start_period: 30s
    volumes:
      - "./data:/data/db"

  api:
    container_name: api-container
    restart: always
    image: node:20
    working_dir: /usr/workspace/cetb-node-api
    command: bash -c "npm install --omit=dev && npm run debug"
    environment:
      - MONGO_URL=mongodb://mongo:27017/cetb-node-api
    volumes: 
      - ./dist/:/usr/workspace/cetb-node-api/dist/
      - ./package.json:/usr/workspace/cetb-node-api/package.json
      - ./assets/:/usr/workspace/cetb-node-api/assets/
    ports: 
      - "4000:4000"
      - "9222:9222"
    links: 
      - mongo

